{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mbe-customer.serviceAccountName" . }}
  labels:
{{ include "mbe-customer.labels" . | nindent 4 }}
{{- end -}}
